sleep 1
echo Current Path: $PWD
sleep 1
echo Downloading key....
wget http://yuzu.api.6100m.ga/WII_NWC_1_CERT.p12
echo Executing patching stage 1...
openssl pkcs12 -in WII_NWC_1_CERT.p12 -out shop.crt -clcerts -nokeys
echo Executing patching stage 2...
openssl pkcs12 -in WII_NWC_1_CERT.p12 -out shop.key -nocerts -nodes
echo Downloading CA....
wget http://yuzu.api.6100m.ga/dst.pem
echo Please specify the .patch file that you want to patch 00000002.app with.
read difffile
echo Please specify the patched 00000002.app file that you want to have the diff patch applied to.
read appfile
echo Patching....
patch $appfile $difffile
echo Patched!
sleep 1
echo Executing setup stage....
mkdir public_html
echo Running backup stage 1...
mkdir old
echo Running backup stage 2...
mv config.go.example old/config.go.example
echo Installing config....
cp old/config.go.example $PWD/config.go
echo Done!
sleep 1
echo Exiting in 10...
sleep 1  # Waits 1 second(s).
echo Exiting in 9...
sleep 1  # Waits 1 second(s).
echo Exiting in 8...
sleep 1  # Waits 1 second(s).
echo Exiting in 7...
sleep 1  # Waits 1 second(s).
echo Exiting in 6...
sleep 1  # Waits 1 second(s).
echo Exiting in 5...
sleep 1  # Waits 1 second(s).
echo Exiting in 4...
sleep 1  # Waits 1 second(s).
echo Exiting in 3...
sleep 1  # Waits 1 second(s).
echo Exiting in 2...
sleep 1  # Waits 1 second(s).
echo Exiting in 1...
sleep 1  # Waits 1 second(s).
exit 0
